/**
 * AI literacy (AI Act art. 4, come modificato dal Digital Omnibus 2026: le
 * aziende "adottano misure per sostenere l'alfabetizzazione in materia di AI"
 * del personale). Contenuto del mini-modulo mostrato con la policy AI
 * aziendale nella pagina pubblica /ack/[token]: regole base e 5 domande a
 * risposta multipla, in inglese, italiano e tedesco. Solo testo statico.
 */
export type LiteracyLang = "en" | "it" | "de";
export const LITERACY_LANGS: LiteracyLang[] = ["en", "it", "de"];
export const LANG_LABEL: Record<LiteracyLang, string> = { en: "English", it: "Italiano", de: "Deutsch" };

export interface LiteracyQuestion {
  id: string;
  q: string;
  options: string[];
  correct: number; // indice in options
  why: string;
}

export interface LiteracyContent {
  ui: {
    title: string;
    intro: (org: string) => string;
    policyHeading: string;
    rulesHeading: string;
    approvedHeading: string;
    notAllowedHeading: string;
    companyRulesHeading: string;
    quizHeading: string;
    quizIntro: string;
    button: string;
    answerAll: string;
    doneTitle: string;
    doneBody: (score: number, total: number) => string;
    alreadyDone: (date: string) => string;
    invalidTitle: string;
    invalidBody: string;
    footer: string;
    correctLabel: string;
    yourAnswer: string;
    none: string;
  };
  rules: string[];
  questions: LiteracyQuestion[];
}

const EN: LiteracyContent = {
  ui: {
    title: "Our AI policy",
    intro: (org) => `${org} asks everyone who works with AI tools to read these rules and take a 2-minute check. It's part of how the company supports AI literacy (EU AI Act, art. 4).`,
    policyHeading: "The policy",
    rulesHeading: "Basic rules for everyone",
    approvedHeading: "AI tools you can use for work",
    notAllowedHeading: "AI tools that are not allowed",
    companyRulesHeading: "Company rules",
    quizHeading: "Quick check — 5 questions",
    quizIntro: "Pick one answer for each question. You'll see the right answers afterwards.",
    button: "I have read and understood",
    answerAll: "Please answer all 5 questions.",
    doneTitle: "Thank you — recorded",
    doneBody: (s, t) => `You answered ${s} of ${t} correctly. Your acknowledgement has been recorded. Here are the answers:`,
    alreadyDone: (d) => `You already confirmed this policy on ${d}.`,
    invalidTitle: "This link isn't valid any more",
    invalidBody: "It may have been replaced by a newer version of the policy. Ask your IT team for a new link.",
    footer: "angar only records that you confirmed the policy and your quiz score — nothing else.",
    correctLabel: "Correct answer",
    yourAnswer: "Your answer",
    none: "None listed yet — ask your IT team.",
  },
  rules: [
    "Use only the AI tools the company has approved for work.",
    "Never enter personal data, customer data, confidential documents or source code into an AI tool that isn't approved.",
    "Check what AI produces: it can be wrong, out of date or biased. You are responsible for what you use.",
    "Tell people when they are talking to an AI or when content was generated by AI.",
    "Don't use AI to make decisions about people (hiring, performance, credit) without human review and prior approval.",
    "Report new AI tools you'd like to use, and anything that went wrong, to your IT team.",
  ],
  questions: [
    {
      id: "q1",
      q: "What should you never paste into an AI tool the company hasn't approved?",
      options: ["A question about an Excel formula", "Customer personal data or a confidential contract", "A paragraph from a public news article"],
      correct: 1,
      why: "Unapproved tools may store or train on what you type. Personal and confidential data must stay in approved tools only (GDPR).",
    },
    {
      id: "q2",
      q: "An AI assistant gives you a confident answer with figures and sources. What do you do?",
      options: ["Use it as it is — it sounds sure", "Ask the AI whether it is sure", "Check the facts and figures before using them"],
      correct: 2,
      why: "AI can invent facts and sources (\"hallucinations\"). A human has to check anything that matters.",
    },
    {
      id: "q3",
      q: "You found a new AI tool that would help your work. What is the right first step?",
      options: ["Ask IT to review and approve it", "Sign up with a personal account and try it on real data", "Use it only on your phone"],
      correct: 0,
      why: "New AI tools must be reviewed first (data, contract, security). Personal accounts put company data outside company control.",
    },
    {
      id: "q4",
      q: "When must you tell people that content or a conversation involves AI?",
      options: ["Never — it's an internal matter", "When people could think a human made it: chatbots, AI-generated images, audio or video", "Only for long texts"],
      correct: 1,
      why: "The AI Act requires transparency (art. 50): people must know when they interact with AI and when content is AI-generated.",
    },
    {
      id: "q5",
      q: "Which of these AI uses is \"high-risk\" under the EU AI Act?",
      options: ["Correcting spelling in an email", "Summarising a public web page", "Screening CVs or evaluating employees"],
      correct: 2,
      why: "AI used in employment decisions is listed in Annex III (high-risk): it needs extra controls and human oversight.",
    },
  ],
};

const IT: LiteracyContent = {
  ui: {
    title: "La nostra policy sull'AI",
    intro: (org) => `${org} chiede a chi usa strumenti di AI di leggere queste regole e fare una verifica di 2 minuti. Fa parte delle misure dell'azienda per l'alfabetizzazione in materia di AI (AI Act UE, art. 4).`,
    policyHeading: "La policy",
    rulesHeading: "Regole base per tutti",
    approvedHeading: "Strumenti di AI che puoi usare per lavoro",
    notAllowedHeading: "Strumenti di AI non consentiti",
    companyRulesHeading: "Regole aziendali",
    quizHeading: "Verifica veloce — 5 domande",
    quizIntro: "Scegli una risposta per ogni domanda. Dopo vedrai quelle corrette.",
    button: "Ho letto e compreso",
    answerAll: "Rispondi a tutte e 5 le domande.",
    doneTitle: "Grazie — registrato",
    doneBody: (s, t) => `Hai risposto correttamente a ${s} domande su ${t}. La tua presa visione è stata registrata. Ecco le risposte:`,
    alreadyDone: (d) => `Hai già confermato questa policy il ${d}.`,
    invalidTitle: "Questo link non è più valido",
    invalidBody: "Potrebbe essere stato sostituito da una versione più recente della policy. Chiedi un nuovo link al tuo team IT.",
    footer: "angar registra solo che hai confermato la policy e il punteggio della verifica — nient'altro.",
    correctLabel: "Risposta corretta",
    yourAnswer: "La tua risposta",
    none: "Nessuno indicato — chiedi al tuo team IT.",
  },
  rules: [
    "Usa per lavoro solo gli strumenti di AI approvati dall'azienda.",
    "Non inserire mai dati personali, dati dei clienti, documenti riservati o codice sorgente in uno strumento di AI non approvato.",
    "Controlla ciò che produce l'AI: può essere sbagliato, non aggiornato o distorto. Sei tu responsabile di ciò che usi.",
    "Informa le persone quando parlano con un'AI o quando un contenuto è generato dall'AI.",
    "Non usare l'AI per decisioni sulle persone (assunzioni, valutazioni, credito) senza revisione umana e approvazione preventiva.",
    "Segnala al team IT i nuovi strumenti di AI che vorresti usare e qualsiasi problema.",
  ],
  questions: [
    {
      id: "q1",
      q: "Cosa non devi mai incollare in uno strumento di AI non approvato dall'azienda?",
      options: ["Una domanda su una formula di Excel", "Dati personali di clienti o un contratto riservato", "Un paragrafo di un articolo di giornale pubblico"],
      correct: 1,
      why: "Gli strumenti non approvati possono conservare ciò che scrivi o usarlo per l'addestramento. I dati personali e riservati restano solo negli strumenti approvati (GDPR).",
    },
    {
      id: "q2",
      q: "Un assistente AI ti dà una risposta sicura, con numeri e fonti. Cosa fai?",
      options: ["La uso così com'è — sembra sicura", "Chiedo all'AI se è sicura", "Verifico fatti e numeri prima di usarli"],
      correct: 2,
      why: "L'AI può inventare fatti e fonti (\"allucinazioni\"). Tutto ciò che conta va verificato da una persona.",
    },
    {
      id: "q3",
      q: "Hai trovato un nuovo strumento di AI utile per il tuo lavoro. Qual è il primo passo giusto?",
      options: ["Chiedere all'IT di valutarlo e approvarlo", "Registrarmi con un account personale e provarlo su dati reali", "Usarlo solo dal telefono"],
      correct: 0,
      why: "I nuovi strumenti di AI vanno prima valutati (dati, contratto, sicurezza). Gli account personali portano i dati aziendali fuori dal controllo dell'azienda.",
    },
    {
      id: "q4",
      q: "Quando devi dire alle persone che un contenuto o una conversazione coinvolge l'AI?",
      options: ["Mai — è una questione interna", "Quando potrebbero pensare che sia opera di una persona: chatbot, immagini, audio o video generati", "Solo per i testi lunghi"],
      correct: 1,
      why: "L'AI Act impone la trasparenza (art. 50): le persone devono sapere quando interagiscono con un'AI e quando un contenuto è generato dall'AI.",
    },
    {
      id: "q5",
      q: "Quale di questi usi dell'AI è \"ad alto rischio\" secondo l'AI Act?",
      options: ["Correggere l'ortografia di un'email", "Riassumere una pagina web pubblica", "Selezionare CV o valutare dipendenti"],
      correct: 2,
      why: "L'AI usata per decisioni sul lavoro è nell'Allegato III (alto rischio): servono controlli aggiuntivi e supervisione umana.",
    },
  ],
};

const DE: LiteracyContent = {
  ui: {
    title: "Unsere KI-Richtlinie",
    intro: (org) => `${org} bittet alle, die mit KI-Tools arbeiten, diese Regeln zu lesen und einen 2-Minuten-Check zu machen. Das gehört zu den Maßnahmen des Unternehmens zur Förderung der KI-Kompetenz (EU AI Act, Art. 4).`,
    policyHeading: "Die Richtlinie",
    rulesHeading: "Grundregeln für alle",
    approvedHeading: "KI-Tools, die du für die Arbeit nutzen darfst",
    notAllowedHeading: "Nicht erlaubte KI-Tools",
    companyRulesHeading: "Unternehmensregeln",
    quizHeading: "Kurzer Check — 5 Fragen",
    quizIntro: "Wähle bei jeder Frage eine Antwort. Danach siehst du die richtigen Antworten.",
    button: "Ich habe gelesen und verstanden",
    answerAll: "Bitte beantworte alle 5 Fragen.",
    doneTitle: "Danke — gespeichert",
    doneBody: (s, t) => `Du hast ${s} von ${t} Fragen richtig beantwortet. Deine Bestätigung wurde gespeichert. Hier die Antworten:`,
    alreadyDone: (d) => `Du hast diese Richtlinie bereits am ${d} bestätigt.`,
    invalidTitle: "Dieser Link ist nicht mehr gültig",
    invalidBody: "Er wurde vielleicht durch eine neuere Version der Richtlinie ersetzt. Frag dein IT-Team nach einem neuen Link.",
    footer: "angar speichert nur, dass du die Richtlinie bestätigt hast, und dein Ergebnis — sonst nichts.",
    correctLabel: "Richtige Antwort",
    yourAnswer: "Deine Antwort",
    none: "Noch nichts festgelegt — frag dein IT-Team.",
  },
  rules: [
    "Nutze für die Arbeit nur die KI-Tools, die das Unternehmen freigegeben hat.",
    "Gib niemals personenbezogene Daten, Kundendaten, vertrauliche Dokumente oder Quellcode in ein nicht freigegebenes KI-Tool ein.",
    "Prüfe, was die KI erzeugt: Es kann falsch, veraltet oder verzerrt sein. Du bist verantwortlich für das, was du verwendest.",
    "Sag Menschen, wenn sie mit einer KI sprechen oder wenn Inhalte von einer KI erzeugt wurden.",
    "Triff mit KI keine Entscheidungen über Personen (Einstellung, Leistung, Kredit) ohne menschliche Prüfung und vorherige Freigabe.",
    "Melde neue KI-Tools, die du nutzen möchtest, und jeden Vorfall deinem IT-Team.",
  ],
  questions: [
    {
      id: "q1",
      q: "Was darfst du niemals in ein nicht freigegebenes KI-Tool einfügen?",
      options: ["Eine Frage zu einer Excel-Formel", "Personenbezogene Kundendaten oder einen vertraulichen Vertrag", "Einen Absatz aus einem öffentlichen Zeitungsartikel"],
      correct: 1,
      why: "Nicht freigegebene Tools können Eingaben speichern oder damit trainieren. Personenbezogene und vertrauliche Daten gehören nur in freigegebene Tools (DSGVO).",
    },
    {
      id: "q2",
      q: "Ein KI-Assistent gibt dir eine selbstsichere Antwort mit Zahlen und Quellen. Was tust du?",
      options: ["Ich übernehme sie so — sie klingt sicher", "Ich frage die KI, ob sie sicher ist", "Ich prüfe Fakten und Zahlen, bevor ich sie verwende"],
      correct: 2,
      why: "KI kann Fakten und Quellen erfinden („Halluzinationen“). Alles Wichtige muss ein Mensch prüfen.",
    },
    {
      id: "q3",
      q: "Du hast ein neues KI-Tool gefunden, das dir bei der Arbeit helfen würde. Was ist der richtige erste Schritt?",
      options: ["Die IT bitten, es zu prüfen und freizugeben", "Mit einem privaten Konto anmelden und mit echten Daten testen", "Es nur auf dem Handy nutzen"],
      correct: 0,
      why: "Neue KI-Tools müssen zuerst geprüft werden (Daten, Vertrag, Sicherheit). Private Konten bringen Unternehmensdaten aus der Kontrolle des Unternehmens.",
    },
    {
      id: "q4",
      q: "Wann musst du Menschen sagen, dass ein Inhalt oder ein Gespräch KI beinhaltet?",
      options: ["Nie — das ist eine interne Sache", "Wenn sie denken könnten, ein Mensch habe es gemacht: Chatbots, KI-generierte Bilder, Audio oder Video", "Nur bei langen Texten"],
      correct: 1,
      why: "Der AI Act verlangt Transparenz (Art. 50): Menschen müssen wissen, wann sie mit KI interagieren und wann Inhalte KI-generiert sind.",
    },
    {
      id: "q5",
      q: "Welche dieser KI-Nutzungen gilt nach dem EU AI Act als „hochriskant“?",
      options: ["Rechtschreibkorrektur in einer E-Mail", "Zusammenfassung einer öffentlichen Webseite", "Lebensläufe sichten oder Mitarbeitende bewerten"],
      correct: 2,
      why: "KI für Beschäftigungsentscheidungen steht in Anhang III (hohes Risiko): Sie braucht zusätzliche Kontrollen und menschliche Aufsicht.",
    },
  ],
};

export const LITERACY: Record<LiteracyLang, LiteracyContent> = { en: EN, it: IT, de: DE };
export const QUIZ_TOTAL = EN.questions.length;

const IT_COUNTRIES = ["it", "italy", "italia", "sm", "san marino", "va"];
const DE_COUNTRIES = ["de", "germany", "deutschland", "at", "austria", "österreich", "li", "liechtenstein"];

/** Lingua dalla query (?lang=it) o, in mancanza, dal paese dell'azienda. */
export function pickLang(requested: string | null | undefined, country: string | null | undefined): LiteracyLang {
  const r = String(requested ?? "").toLowerCase().slice(0, 2);
  if ((LITERACY_LANGS as string[]).includes(r)) return r as LiteracyLang;
  const c = String(country ?? "").trim().toLowerCase();
  if (IT_COUNTRIES.includes(c)) return "it";
  if (DE_COUNTRIES.includes(c)) return "de";
  return "en";
}

/** Punteggio: risposte corrette su QUIZ_TOTAL. `answers[qId]` = indice scelto. */
export function scoreQuiz(answers: Record<string, number | null | undefined>, lang: LiteracyLang = "en"): number {
  return LITERACY[lang].questions.reduce((n, q) => n + (answers[q.id] === q.correct ? 1 : 0), 0);
}
