import Link from "next/link";
import { requireRole } from "@/lib/auth";
import { buildEvidencePack, packFingerprint } from "@/lib/evidence-pack";
import { PageHeader, Table, td } from "@/components/ui";
import PrintButton from "@/components/PrintButton";
import PrivacyNotice from "@/components/PrivacyNotice";
import { fmtDate, fmtDateTime } from "@/lib/format";

export const dynamic = "force-dynamic";

const STATUS_LABEL: Record<string, string> = { APPROVED: "Allowed", UNAPPROVED: "Not allowed", UNREVIEWED: "To review", UNKNOWN: "To review" };
const type = (t: string) => t.replace(/_/g, " ").toLowerCase().replace(/^\w/, (m) => m.toUpperCase());
const short = (h: string | null) => (h ? `${h.slice(0, 12)}…` : "—");

// Evidence pack AI Act / NIS2: stampabile (PDF) e scaricabile in JSON con impronta SHA-256.
export default async function EvidencePackPage() {
  const s = await requireRole("ADMIN", "/compliance");
  const pack = await buildEvidencePack(s.orgId, s.email);
  const fingerprint = packFingerprint(pack);
  const c = pack.auditLog.chain;

  return (
    <div className="flex flex-col gap-6">
      <div className="print:hidden">
        <PageHeader
          crumbs={[{ label: "AI Act", href: "/compliance" }, { label: "Evidence pack" }]}
          title="Evidence pack"
          subtitle="AI Act and NIS2 evidence in one document: AI inventory, readiness, training, policies, controls, suppliers, incidents and a tamper-evident audit log."
          action={
            <>
              <a href="/api/compliance/evidence" className="btn btn-secondary">Download JSON</a>
              <PrintButton label="Print / PDF" />
            </>
          }
        />
      </div>
      <div className="print:hidden">
        <PrivacyNotice mode={pack.organisation.privacyMode} what="The evidence pack" />
      </div>

      <section className="rounded-xl border border-line bg-panel p-5">
        <h1 className="text-xl font-semibold text-ink-100">AI Act / NIS2 evidence pack — {pack.organisation.name}</h1>
        <dl className="mt-3 grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-1.5 text-sm">
          <Row label="Organisation" value={pack.organisation.name} />
          <Row label="Country" value={pack.organisation.country ?? "—"} />
          <Row label="Employees" value={pack.organisation.employees ? String(pack.organisation.employees) : "—"} />
          <Row label="Industry" value={pack.organisation.industry ?? "—"} />
          <Row label="Generated at" value={`${fmtDateTime(new Date(pack.generatedAt))} (${pack.generatedAt})`} />
          <Row label="Generated by" value={pack.generatedBy ?? "—"} />
          <Row label="Employee privacy mode" value={pack.organisation.privacyMode} />
        </dl>
        <p className="mt-3 text-xs text-ink-400 break-all">
          Fingerprint (SHA-256 of this pack&apos;s canonical JSON): <span className="font-mono text-ink-100">{fingerprint}</span>
        </p>
        <p className="mt-1 text-xs text-ink-400">The JSON download is generated separately and carries its own fingerprint.</p>
      </section>

      <Section title="1. AI inventory" subtitle={`${pack.aiInventory.length} AI systems (EU AI Act Art. 26 deployer duties; NIS2 Art. 21 asset management).`}>
        <Table columns={["AI", "Vendor", "Type", "Status", "EU AI Act", "Owner / department", "First seen", "Sources"]} empty={pack.aiInventory.length ? false : "No AI found yet."}>
          {pack.aiInventory.map((a) => (
            <tr key={a.name + a.firstSeen}>
              <td className={`${td} font-medium text-ink-100`}>{a.name}</td>
              <td className={`${td} text-ink-400`}>{a.vendor ?? "—"}</td>
              <td className={`${td} text-ink-400`}>{type(a.type)}</td>
              <td className={`${td} text-ink-400`}>{STATUS_LABEL[a.status] ?? a.status}</td>
              <td className={`${td} text-ink-100`}>{a.euAiActTier}</td>
              <td className={`${td} text-ink-400`}>{[a.owner, a.department].filter(Boolean).join(" · ") || "—"}</td>
              <td className={`${td} text-ink-400 tabular whitespace-nowrap`}>{fmtDate(new Date(a.firstSeen))}</td>
              <td className={`${td} text-xs text-ink-400`}>{a.sources.join(", ") || "Manual"}</td>
            </tr>
          ))}
        </Table>
      </Section>

      <Section title="2. AI Act readiness" subtitle={`Score ${pack.aiActReadiness.score}/100 · ${pack.aiActReadiness.classified}/${pack.aiActReadiness.total} classified · ${pack.aiActReadiness.highRisk} high-risk · ${pack.aiActReadiness.missingOwners} missing owners`}>
        <Table columns={["Check", "Detail", { label: "Points", className: "text-right" }]}>
          {pack.aiActReadiness.checks.map((x) => (
            <tr key={x.key}>
              <td className={`${td} text-ink-100`}>{x.label}</td>
              <td className={`${td} text-ink-400`}>{x.detail}</td>
              <td className={`${td} text-right tabular text-ink-100`}>{x.points}/{x.weight}</td>
            </tr>
          ))}
        </Table>
      </Section>

      <Section title="3. AI literacy (Art. 4)" subtitle="Training recorded in angar.">
        <Table columns={["Date", "Training", "Recorded by"]} empty={pack.aiLiteracy.length ? false : "No AI literacy training recorded — record it on the AI Act page."}>
          {pack.aiLiteracy.map((l, i) => (
            <tr key={i}>
              <td className={`${td} text-ink-400 tabular whitespace-nowrap`}>{fmtDate(new Date(l.date))}</td>
              <td className={`${td} text-ink-100`}>{l.summary}</td>
              <td className={`${td} text-ink-400`}>{l.recordedBy ?? "—"}</td>
            </tr>
          ))}
        </Table>
      </Section>

      <Section title="4. Policies">
        <Table columns={["Policy", "Category", "Status", "Last updated"]} empty={pack.policies.length ? false : "No policies yet."}>
          {pack.policies.map((p) => (
            <tr key={p.name}>
              <td className={td}>
                <div className="text-ink-100">{p.name}</div>
                <div className="text-xs text-ink-400">{p.description}</div>
              </td>
              <td className={`${td} text-ink-400`}>{type(p.category)}</td>
              <td className={`${td} ${p.enabled ? "text-steady" : "text-ink-400"}`}>{p.enabled ? "Enabled" : "Disabled"}</td>
              <td className={`${td} text-ink-400 tabular whitespace-nowrap`}>{fmtDate(new Date(p.updatedAt))}</td>
            </tr>
          ))}
        </Table>
      </Section>

      <Section title="5. Network controls" subtitle={`AI blocked on the company network with angar Edge · Sensors: ${pack.edgeSensors.total} (${pack.edgeSensors.online} online)${pack.edgeSensors.lastSeen ? `, last report ${fmtDateTime(new Date(pack.edgeSensors.lastSeen))}` : ""}`}>
        <Table columns={["Blocked AI", "Vendor", "Suggested instead"]} empty={pack.networkControls.length ? false : "No AI is blocked on the network."}>
          {pack.networkControls.map((n) => (
            <tr key={n.name}>
              <td className={`${td} text-ink-100`}>{n.name}</td>
              <td className={`${td} text-ink-400`}>{n.vendor ?? "—"}</td>
              <td className={`${td} text-ink-400`}>{n.suggestedInstead ?? "—"}</td>
            </tr>
          ))}
        </Table>
      </Section>

      <Section title="6. NIS2 — AI services as ICT third-party providers" subtitle="Supply-chain security (NIS2 Art. 21(2)(d)): every AI vendor, its services and the company data they can reach.">
        <Table columns={["Vendor", "Services", { label: "Allowed", className: "text-right" }, { label: "Not allowed", className: "text-right" }, { label: "To review", className: "text-right" }, "Data access"]} empty={pack.nis2.ictThirdPartyProviders.length ? false : "No AI vendors yet."}>
          {pack.nis2.ictThirdPartyProviders.map((v) => (
            <tr key={v.vendor}>
              <td className={`${td} font-medium text-ink-100`}>{v.vendor}</td>
              <td className={`${td} text-ink-400`}>{v.services.join(", ")}</td>
              <td className={`${td} text-right tabular text-ink-100`}>{v.approved}</td>
              <td className={`${td} text-right tabular ${v.notAllowed ? "text-alarm" : "text-ink-400"}`}>{v.notAllowed}</td>
              <td className={`${td} text-right tabular text-ink-400`}>{v.toReview}</td>
              <td className={`${td} text-xs text-ink-400`}>{v.dataAccess.map((d) => `${d.name} (${d.sensitivity.toLowerCase()})`).join(", ") || "None declared"}</td>
            </tr>
          ))}
        </Table>
      </Section>

      <Section title="7. NIS2 — critical incidents and alerts, last 12 months">
        <Table columns={["Date", "Kind", "Alert"]} empty={pack.nis2.criticalIncidents.length ? false : "No critical alerts in the last 12 months."}>
          {pack.nis2.criticalIncidents.map((a, i) => (
            <tr key={i}>
              <td className={`${td} text-ink-400 tabular whitespace-nowrap`}>{fmtDateTime(new Date(a.date))}</td>
              <td className={`${td} text-ink-400`}>{type(a.kind)}</td>
              <td className={td}>
                <div className="text-ink-100">{a.title}</div>
                {a.body && <div className="text-xs text-ink-400">{a.body}</div>}
              </td>
            </tr>
          ))}
        </Table>
      </Section>

      <Section title="8. Audit log integrity" subtitle="Every audit entry carries the SHA-256 of the previous one: changing, deleting or inserting an entry breaks the chain.">
        <div className={`rounded-xl px-4 py-3 text-sm ${c.ok ? "bg-steady/10 text-steady" : "bg-alarm/10 text-alarm"}`}>
          {c.ok ? (
            <>
              <b>Chain intact.</b> {c.checked} chained {c.checked === 1 ? "entry" : "entries"} verified
              {c.legacyUnchained ? `; ${c.legacyUnchained} older ${c.legacyUnchained === 1 ? "entry was" : "entries were"} written before chaining (legacy, not verifiable)` : ""}.
              {c.headHash && <span className="block text-xs font-mono mt-1 break-all">Head: {c.headHash}</span>}
            </>
          ) : (
            <>
              <b>Chain broken</b> at entry <span className="font-mono">{c.firstBrokenId}</span>: {c.brokenReason}. {c.checked} entries verified before it.
            </>
          )}
        </div>
        <div className="mt-3">
          <Table columns={["When", "Who", "Action", "Target", "Hash", "Previous"]} empty={pack.auditLog.lastEntries.length ? false : "Nothing recorded yet."}>
            {pack.auditLog.lastEntries.map((e, i) => (
              <tr key={i}>
                <td className={`${td} tabular text-ink-400 whitespace-nowrap`}>{fmtDateTime(new Date(e.at))}</td>
                <td className={`${td} text-ink-100`}>{e.actor ?? "—"}</td>
                <td className={`${td} font-mono text-xs text-ink-100`}>{e.action}</td>
                <td className={`${td} text-ink-400 max-w-[220px] truncate`}>{e.target ?? "—"}</td>
                <td className={`${td} font-mono text-xs text-ink-400`} title={e.hash ?? "Legacy entry (before chaining)"}>{e.hash ? short(e.hash) : "legacy"}</td>
                <td className={`${td} font-mono text-xs text-ink-400`} title={e.prevHash ?? ""}>{short(e.prevHash)}</td>
              </tr>
            ))}
          </Table>
        </div>
        <p className="text-xs text-ink-400 mt-2">
          Full hashes are in the JSON download. Full log: <Link href="/audit" className="underline hover:text-ink-100">Audit log</Link>.
        </p>
      </Section>

      <p className="text-xs text-ink-400">Generated by angar from its database — not legal advice. Confirm high-risk cases and NIS2 scope with your DPO or counsel.</p>
    </div>
  );
}

function Section({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) {
  return (
    <section className="flex flex-col gap-3">
      <div>
        <h2 className="text-base font-semibold text-ink-100">{title}</h2>
        {subtitle && <p className="text-sm text-ink-400">{subtitle}</p>}
      </div>
      {children}
    </section>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-baseline justify-between gap-3 border-b border-line py-1">
      <dt className="text-ink-400">{label}</dt>
      <dd className="text-ink-100 text-right">{value}</dd>
    </div>
  );
}
